# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0546226b479b6001aefc06a25e8a3ee4e19b7d7b53570e89d104d7fdad088cc34019534ae0ac342cd2c04f0a3c95ff085abbbf45ea723be9df831d810ef53d9b

test:
  secret_key_base: f6562085dc55b53a4eb59f1154e465022670e9cb902ed8917659e6a2ea0a4dc662b1a4af8cee09bfc82eae2ea3e807ad762bf6013dc039cab963237962849aef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
